# Generated by Django 3.2 on 2021-06-17 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('categoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('categoryName', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='aptitude/images')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('subCategoryId', models.IntegerField(primary_key=True, serialize=False)),
                ('subCategoryName', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, upload_to='aptitude/images')),
                ('categoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptitude.category')),
            ],
        ),
        migrations.CreateModel(
            name='questionBank',
            fields=[
                ('questionId', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('answer', models.CharField(max_length=5)),
                ('subCategoryId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aptitude.subcategory')),
            ],
        ),
    ]
