# Generated by Django 3.2 on 2021-06-23 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='questionId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aptitude.questionbank'),
        ),
    ]
