# Generated by Django 3.2 on 2021-06-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aptitude', '0003_category_iconname'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='Content', max_length=300),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.CharField(default='Content', max_length=300),
        ),
    ]
